// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drrtjksrurkrbgmxstbv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRycnRqa3NydXJrcmJnbXhzdGJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg1MTkwODgsImV4cCI6MjA5NDA5NTA4OH0.JtxpNo5gXdnhhKW2wfqA7YFXQqHmpydbBmgASJj0Cjo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});